= Parameters

The parent key for all of the following parameters is `openshift4_version`.

== `spec`



[horizontal]
type:: object
default::
+
[source,yaml]
----
channel: stable-4.8
upstream: https://api.openshift.com/api/upgrades_info/v1/graph
----

See the https://docs.openshift.com/container-platform/latest/updating/updating-cluster-between-minor.html[OpenShift docs] for available parameters and values.

[NOTE]
====
Field `clusterID` must be set in the `ClusterVersion` object.
The value for this field is supposed to be extracted from the cluster as a fact.
However, the corresponding dynamic fact isn't implemented yet.
We recommend that users set `spec.clusterID` to a non-component parameter such as `openshift.clusterID` in the config hierarchy.
====

== Example

We recommend configuring a reference for component parameter `openshift4_version.spec.clusterID` for all OpenShift 4 clusters:

.openshift4.yml
[source,yaml]
----
parameters:
  openshift:
    clusterID: 'OVERRIDE_THIS_IN_THE_CLUSTER_CONFIG'
  openshift4_version:
    spec:
      clusterID: ${openshift.clusterID}
----

With this approach, each individual cluster config only needs to set generic parameter `openshift.clusterID`.

.cluster.yml
[source,yaml]
----
parameters:
  openshift:
    clusterID: '6d8329e3-7098-4bab-b7d8-11f1dc353481'

  openshift4_version:
    spec:
      desiredUpdate:
        force: false
        image: quay.io/openshift-release-dev/ocp-release@sha256:7613d8f7db639147b91b16b54b24cfa351c3cbde6aa7b7bf1b9c80c260efad06
        version: 4.4.6
----

[NOTE]
====
This example assumes that `openshift4_version.spec.clusterID` is set to `${openshift.clusterID}` somewhere in the inventory.
Due to https://github.com/projectsyn/commodore/issues/138, this can not yet be done in the defaults.
====
